// source: modules/v2x/proto/v2x_monitor.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.apollo.v2x.ErrorCode', null, global);
goog.exportSymbol('proto.apollo.v2x.ObuAlarm', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.v2x.ObuAlarm = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apollo.v2x.ObuAlarm, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.v2x.ObuAlarm.displayName = 'proto.apollo.v2x.ObuAlarm';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.v2x.ObuAlarm.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.v2x.ObuAlarm.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.v2x.ObuAlarm} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.v2x.ObuAlarm.toObject = function(includeInstance, msg) {
  var f, obj = {
    modeNum: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    errorNum: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    errorMsg: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of ObuAlarm as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.v2x.ObuAlarm.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.modeNum;

  /** @type {?|undefined} */
  this.errorNum;

  /** @type {?|undefined} */
  this.errorMsg;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.v2x.ObuAlarm.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.v2x.ObuAlarm}
 */
proto.apollo.v2x.ObuAlarm.fromObject = function(obj) {
  var msg = new proto.apollo.v2x.ObuAlarm();
  obj.modeNum != null && jspb.Message.setField(msg, 1, obj.modeNum);
  obj.errorNum != null && jspb.Message.setField(msg, 2, obj.errorNum);
  obj.errorMsg != null && jspb.Message.setField(msg, 3, obj.errorMsg);
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.v2x.ObuAlarm}
 */
proto.apollo.v2x.ObuAlarm.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.v2x.ObuAlarm;
  return proto.apollo.v2x.ObuAlarm.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.v2x.ObuAlarm} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.v2x.ObuAlarm}
 */
proto.apollo.v2x.ObuAlarm.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setModeNum(value);
      break;
    case 2:
      var value = /** @type {!proto.apollo.v2x.ErrorCode} */ (reader.readEnum());
      msg.setErrorNum(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.v2x.ObuAlarm.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.v2x.ObuAlarm.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.v2x.ObuAlarm} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.v2x.ObuAlarm.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {!proto.apollo.v2x.ErrorCode} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * required double mode_num = 1;
 * @return {number}
 */
proto.apollo.v2x.ObuAlarm.prototype.getModeNum = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.setModeNum = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.clearModeNum = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.v2x.ObuAlarm.prototype.hasModeNum = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required ErrorCode error_num = 2;
 * @return {!proto.apollo.v2x.ErrorCode}
 */
proto.apollo.v2x.ObuAlarm.prototype.getErrorNum = function() {
  return /** @type {!proto.apollo.v2x.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 2, 500));
};


/**
 * @param {!proto.apollo.v2x.ErrorCode} value
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.setErrorNum = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.clearErrorNum = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.v2x.ObuAlarm.prototype.hasErrorNum = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string error_msg = 3;
 * @return {string}
 */
proto.apollo.v2x.ObuAlarm.prototype.getErrorMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.setErrorMsg = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.v2x.ObuAlarm} returns this
 */
proto.apollo.v2x.ObuAlarm.prototype.clearErrorMsg = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.v2x.ObuAlarm.prototype.hasErrorMsg = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.apollo.v2x.ErrorCode = {
  LTEV: 500,
  NET: 501,
  CPU: 502,
  MEM: 503,
  GPS: 504,
  MAP: 510,
  SPAT: 511,
  OBUID: 999
};

goog.object.extend(exports, proto.apollo.v2x);
