// source: modules/localization/proto/localization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var modules_common_proto_header_pb = require('../../../modules/common/proto/header_pb.js');
goog.object.extend(proto, modules_common_proto_header_pb);
var modules_localization_proto_pose_pb = require('../../../modules/localization/proto/pose_pb.js');
goog.object.extend(proto, modules_localization_proto_pose_pb);
var modules_common_proto_geometry_pb = require('../../../modules/common/proto/geometry_pb.js');
goog.object.extend(proto, modules_common_proto_geometry_pb);
var modules_common_proto_pnc_point_pb = require('../../../modules/common/proto/pnc_point_pb.js');
goog.object.extend(proto, modules_common_proto_pnc_point_pb);
var modules_localization_proto_localization_status_pb = require('../../../modules/localization/proto/localization_status_pb.js');
goog.object.extend(proto, modules_localization_proto_localization_status_pb);
goog.exportSymbol('proto.apollo.localization.LocalizationEstimate', null, global);
goog.exportSymbol('proto.apollo.localization.LocalizationStatus', null, global);
goog.exportSymbol('proto.apollo.localization.MeasureState', null, global);
goog.exportSymbol('proto.apollo.localization.Uncertainty', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.localization.Uncertainty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apollo.localization.Uncertainty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.localization.Uncertainty.displayName = 'proto.apollo.localization.Uncertainty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.localization.LocalizationEstimate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.localization.LocalizationEstimate.repeatedFields_, null);
};
goog.inherits(proto.apollo.localization.LocalizationEstimate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.localization.LocalizationEstimate.displayName = 'proto.apollo.localization.LocalizationEstimate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.localization.LocalizationStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apollo.localization.LocalizationStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.localization.LocalizationStatus.displayName = 'proto.apollo.localization.LocalizationStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.localization.Uncertainty.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.localization.Uncertainty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.localization.Uncertainty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.Uncertainty.toObject = function(includeInstance, msg) {
  var f, obj = {
    positionStdDev: (f = msg.getPositionStdDev()) && modules_common_proto_geometry_pb.Point3D.toObject(includeInstance, f),
    orientationStdDev: (f = msg.getOrientationStdDev()) && modules_common_proto_geometry_pb.Point3D.toObject(includeInstance, f),
    linearVelocityStdDev: (f = msg.getLinearVelocityStdDev()) && modules_common_proto_geometry_pb.Point3D.toObject(includeInstance, f),
    linearAccelerationStdDev: (f = msg.getLinearAccelerationStdDev()) && modules_common_proto_geometry_pb.Point3D.toObject(includeInstance, f),
    angularVelocityStdDev: (f = msg.getAngularVelocityStdDev()) && modules_common_proto_geometry_pb.Point3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of Uncertainty as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.localization.Uncertainty.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.positionStdDev;

  /** @type {?|undefined} */
  this.orientationStdDev;

  /** @type {?|undefined} */
  this.linearVelocityStdDev;

  /** @type {?|undefined} */
  this.linearAccelerationStdDev;

  /** @type {?|undefined} */
  this.angularVelocityStdDev;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.localization.Uncertainty.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.localization.Uncertainty}
 */
proto.apollo.localization.Uncertainty.fromObject = function(obj) {
  var msg = new proto.apollo.localization.Uncertainty();
  obj.positionStdDev && jspb.Message.setWrapperField(
      msg, 1, modules_common_proto_geometry_pb.Point3D.fromObject(obj.positionStdDev));
  obj.orientationStdDev && jspb.Message.setWrapperField(
      msg, 2, modules_common_proto_geometry_pb.Point3D.fromObject(obj.orientationStdDev));
  obj.linearVelocityStdDev && jspb.Message.setWrapperField(
      msg, 3, modules_common_proto_geometry_pb.Point3D.fromObject(obj.linearVelocityStdDev));
  obj.linearAccelerationStdDev && jspb.Message.setWrapperField(
      msg, 4, modules_common_proto_geometry_pb.Point3D.fromObject(obj.linearAccelerationStdDev));
  obj.angularVelocityStdDev && jspb.Message.setWrapperField(
      msg, 5, modules_common_proto_geometry_pb.Point3D.fromObject(obj.angularVelocityStdDev));
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.localization.Uncertainty}
 */
proto.apollo.localization.Uncertainty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.localization.Uncertainty;
  return proto.apollo.localization.Uncertainty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.localization.Uncertainty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.localization.Uncertainty}
 */
proto.apollo.localization.Uncertainty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new modules_common_proto_geometry_pb.Point3D;
      reader.readMessage(value,modules_common_proto_geometry_pb.Point3D.deserializeBinaryFromReader);
      msg.setPositionStdDev(value);
      break;
    case 2:
      var value = new modules_common_proto_geometry_pb.Point3D;
      reader.readMessage(value,modules_common_proto_geometry_pb.Point3D.deserializeBinaryFromReader);
      msg.setOrientationStdDev(value);
      break;
    case 3:
      var value = new modules_common_proto_geometry_pb.Point3D;
      reader.readMessage(value,modules_common_proto_geometry_pb.Point3D.deserializeBinaryFromReader);
      msg.setLinearVelocityStdDev(value);
      break;
    case 4:
      var value = new modules_common_proto_geometry_pb.Point3D;
      reader.readMessage(value,modules_common_proto_geometry_pb.Point3D.deserializeBinaryFromReader);
      msg.setLinearAccelerationStdDev(value);
      break;
    case 5:
      var value = new modules_common_proto_geometry_pb.Point3D;
      reader.readMessage(value,modules_common_proto_geometry_pb.Point3D.deserializeBinaryFromReader);
      msg.setAngularVelocityStdDev(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.localization.Uncertainty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.localization.Uncertainty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.localization.Uncertainty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.Uncertainty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPositionStdDev();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      modules_common_proto_geometry_pb.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getOrientationStdDev();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      modules_common_proto_geometry_pb.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getLinearVelocityStdDev();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      modules_common_proto_geometry_pb.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getLinearAccelerationStdDev();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      modules_common_proto_geometry_pb.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getAngularVelocityStdDev();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      modules_common_proto_geometry_pb.Point3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional apollo.common.Point3D position_std_dev = 1;
 * @return {?proto.apollo.common.Point3D}
 */
proto.apollo.localization.Uncertainty.prototype.getPositionStdDev = function() {
  return /** @type{?proto.apollo.common.Point3D} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_geometry_pb.Point3D, 1));
};


/**
 * @param {?proto.apollo.common.Point3D|undefined} value
 * @return {!proto.apollo.localization.Uncertainty} returns this
*/
proto.apollo.localization.Uncertainty.prototype.setPositionStdDev = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.Uncertainty} returns this
 */
proto.apollo.localization.Uncertainty.prototype.clearPositionStdDev = function() {
  return this.setPositionStdDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.Uncertainty.prototype.hasPositionStdDev = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional apollo.common.Point3D orientation_std_dev = 2;
 * @return {?proto.apollo.common.Point3D}
 */
proto.apollo.localization.Uncertainty.prototype.getOrientationStdDev = function() {
  return /** @type{?proto.apollo.common.Point3D} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_geometry_pb.Point3D, 2));
};


/**
 * @param {?proto.apollo.common.Point3D|undefined} value
 * @return {!proto.apollo.localization.Uncertainty} returns this
*/
proto.apollo.localization.Uncertainty.prototype.setOrientationStdDev = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.Uncertainty} returns this
 */
proto.apollo.localization.Uncertainty.prototype.clearOrientationStdDev = function() {
  return this.setOrientationStdDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.Uncertainty.prototype.hasOrientationStdDev = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional apollo.common.Point3D linear_velocity_std_dev = 3;
 * @return {?proto.apollo.common.Point3D}
 */
proto.apollo.localization.Uncertainty.prototype.getLinearVelocityStdDev = function() {
  return /** @type{?proto.apollo.common.Point3D} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_geometry_pb.Point3D, 3));
};


/**
 * @param {?proto.apollo.common.Point3D|undefined} value
 * @return {!proto.apollo.localization.Uncertainty} returns this
*/
proto.apollo.localization.Uncertainty.prototype.setLinearVelocityStdDev = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.Uncertainty} returns this
 */
proto.apollo.localization.Uncertainty.prototype.clearLinearVelocityStdDev = function() {
  return this.setLinearVelocityStdDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.Uncertainty.prototype.hasLinearVelocityStdDev = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional apollo.common.Point3D linear_acceleration_std_dev = 4;
 * @return {?proto.apollo.common.Point3D}
 */
proto.apollo.localization.Uncertainty.prototype.getLinearAccelerationStdDev = function() {
  return /** @type{?proto.apollo.common.Point3D} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_geometry_pb.Point3D, 4));
};


/**
 * @param {?proto.apollo.common.Point3D|undefined} value
 * @return {!proto.apollo.localization.Uncertainty} returns this
*/
proto.apollo.localization.Uncertainty.prototype.setLinearAccelerationStdDev = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.Uncertainty} returns this
 */
proto.apollo.localization.Uncertainty.prototype.clearLinearAccelerationStdDev = function() {
  return this.setLinearAccelerationStdDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.Uncertainty.prototype.hasLinearAccelerationStdDev = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional apollo.common.Point3D angular_velocity_std_dev = 5;
 * @return {?proto.apollo.common.Point3D}
 */
proto.apollo.localization.Uncertainty.prototype.getAngularVelocityStdDev = function() {
  return /** @type{?proto.apollo.common.Point3D} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_geometry_pb.Point3D, 5));
};


/**
 * @param {?proto.apollo.common.Point3D|undefined} value
 * @return {!proto.apollo.localization.Uncertainty} returns this
*/
proto.apollo.localization.Uncertainty.prototype.setAngularVelocityStdDev = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.Uncertainty} returns this
 */
proto.apollo.localization.Uncertainty.prototype.clearAngularVelocityStdDev = function() {
  return this.setAngularVelocityStdDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.Uncertainty.prototype.hasAngularVelocityStdDev = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.localization.LocalizationEstimate.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.localization.LocalizationEstimate.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.localization.LocalizationEstimate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.localization.LocalizationEstimate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.LocalizationEstimate.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && modules_common_proto_header_pb.Header.toObject(includeInstance, f),
    pose: (f = msg.getPose()) && modules_localization_proto_pose_pb.Pose.toObject(includeInstance, f),
    uncertainty: (f = msg.getUncertainty()) && proto.apollo.localization.Uncertainty.toObject(includeInstance, f),
    measurementTime: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    trajectoryPointList: jspb.Message.toObjectList(msg.getTrajectoryPointList(),
    modules_common_proto_pnc_point_pb.TrajectoryPoint.toObject, includeInstance),
    msfStatus: (f = msg.getMsfStatus()) && modules_localization_proto_localization_status_pb.MsfStatus.toObject(includeInstance, f),
    sensorStatus: (f = msg.getSensorStatus()) && modules_localization_proto_localization_status_pb.MsfSensorMsgStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of LocalizationEstimate as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.localization.LocalizationEstimate.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.header;

  /** @type {?|undefined} */
  this.pose;

  /** @type {?|undefined} */
  this.uncertainty;

  /** @type {?|undefined} */
  this.measurementTime;

  /** @type {?|undefined} */
  this.trajectoryPointList;

  /** @type {?|undefined} */
  this.msfStatus;

  /** @type {?|undefined} */
  this.sensorStatus;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.localization.LocalizationEstimate.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.localization.LocalizationEstimate}
 */
proto.apollo.localization.LocalizationEstimate.fromObject = function(obj) {
  var msg = new proto.apollo.localization.LocalizationEstimate();
  obj.header && jspb.Message.setWrapperField(
      msg, 1, modules_common_proto_header_pb.Header.fromObject(obj.header));
  obj.pose && jspb.Message.setWrapperField(
      msg, 2, modules_localization_proto_pose_pb.Pose.fromObject(obj.pose));
  obj.uncertainty && jspb.Message.setWrapperField(
      msg, 3, proto.apollo.localization.Uncertainty.fromObject(obj.uncertainty));
  obj.measurementTime != null && jspb.Message.setField(msg, 4, obj.measurementTime);
  obj.trajectoryPointList && jspb.Message.setRepeatedWrapperField(
      msg, 5, obj.trajectoryPointList.map(
          modules_common_proto_pnc_point_pb.TrajectoryPoint.fromObject));
  obj.msfStatus && jspb.Message.setWrapperField(
      msg, 6, modules_localization_proto_localization_status_pb.MsfStatus.fromObject(obj.msfStatus));
  obj.sensorStatus && jspb.Message.setWrapperField(
      msg, 7, modules_localization_proto_localization_status_pb.MsfSensorMsgStatus.fromObject(obj.sensorStatus));
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.localization.LocalizationEstimate}
 */
proto.apollo.localization.LocalizationEstimate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.localization.LocalizationEstimate;
  return proto.apollo.localization.LocalizationEstimate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.localization.LocalizationEstimate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.localization.LocalizationEstimate}
 */
proto.apollo.localization.LocalizationEstimate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new modules_common_proto_header_pb.Header;
      reader.readMessage(value,modules_common_proto_header_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new modules_localization_proto_pose_pb.Pose;
      reader.readMessage(value,modules_localization_proto_pose_pb.Pose.deserializeBinaryFromReader);
      msg.setPose(value);
      break;
    case 3:
      var value = new proto.apollo.localization.Uncertainty;
      reader.readMessage(value,proto.apollo.localization.Uncertainty.deserializeBinaryFromReader);
      msg.setUncertainty(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMeasurementTime(value);
      break;
    case 5:
      var value = new modules_common_proto_pnc_point_pb.TrajectoryPoint;
      reader.readMessage(value,modules_common_proto_pnc_point_pb.TrajectoryPoint.deserializeBinaryFromReader);
      msg.addTrajectoryPoint(value);
      break;
    case 6:
      var value = new modules_localization_proto_localization_status_pb.MsfStatus;
      reader.readMessage(value,modules_localization_proto_localization_status_pb.MsfStatus.deserializeBinaryFromReader);
      msg.setMsfStatus(value);
      break;
    case 7:
      var value = new modules_localization_proto_localization_status_pb.MsfSensorMsgStatus;
      reader.readMessage(value,modules_localization_proto_localization_status_pb.MsfSensorMsgStatus.deserializeBinaryFromReader);
      msg.setSensorStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.localization.LocalizationEstimate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.localization.LocalizationEstimate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.localization.LocalizationEstimate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.LocalizationEstimate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      modules_common_proto_header_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getPose();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      modules_localization_proto_pose_pb.Pose.serializeBinaryToWriter
    );
  }
  f = message.getUncertainty();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.apollo.localization.Uncertainty.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getTrajectoryPointList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      modules_common_proto_pnc_point_pb.TrajectoryPoint.serializeBinaryToWriter
    );
  }
  f = message.getMsfStatus();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      modules_localization_proto_localization_status_pb.MsfStatus.serializeBinaryToWriter
    );
  }
  f = message.getSensorStatus();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      modules_localization_proto_localization_status_pb.MsfSensorMsgStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional apollo.common.Header header = 1;
 * @return {?proto.apollo.common.Header}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getHeader = function() {
  return /** @type{?proto.apollo.common.Header} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_header_pb.Header, 1));
};


/**
 * @param {?proto.apollo.common.Header|undefined} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Pose pose = 2;
 * @return {?proto.apollo.localization.Pose}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getPose = function() {
  return /** @type{?proto.apollo.localization.Pose} */ (
    jspb.Message.getWrapperField(this, modules_localization_proto_pose_pb.Pose, 2));
};


/**
 * @param {?proto.apollo.localization.Pose|undefined} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setPose = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearPose = function() {
  return this.setPose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasPose = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Uncertainty uncertainty = 3;
 * @return {?proto.apollo.localization.Uncertainty}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getUncertainty = function() {
  return /** @type{?proto.apollo.localization.Uncertainty} */ (
    jspb.Message.getWrapperField(this, proto.apollo.localization.Uncertainty, 3));
};


/**
 * @param {?proto.apollo.localization.Uncertainty|undefined} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setUncertainty = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearUncertainty = function() {
  return this.setUncertainty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasUncertainty = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double measurement_time = 4;
 * @return {number}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getMeasurementTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.setMeasurementTime = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearMeasurementTime = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasMeasurementTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated apollo.common.TrajectoryPoint trajectory_point = 5;
 * @return {!Array<!proto.apollo.common.TrajectoryPoint>}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getTrajectoryPointList = function() {
  return /** @type{!Array<!proto.apollo.common.TrajectoryPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, modules_common_proto_pnc_point_pb.TrajectoryPoint, 5));
};


/**
 * @param {!Array<!proto.apollo.common.TrajectoryPoint>} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setTrajectoryPointList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.apollo.common.TrajectoryPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.apollo.common.TrajectoryPoint}
 */
proto.apollo.localization.LocalizationEstimate.prototype.addTrajectoryPoint = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.apollo.common.TrajectoryPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearTrajectoryPointList = function() {
  return this.setTrajectoryPointList([]);
};


/**
 * optional MsfStatus msf_status = 6;
 * @return {?proto.apollo.localization.MsfStatus}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getMsfStatus = function() {
  return /** @type{?proto.apollo.localization.MsfStatus} */ (
    jspb.Message.getWrapperField(this, modules_localization_proto_localization_status_pb.MsfStatus, 6));
};


/**
 * @param {?proto.apollo.localization.MsfStatus|undefined} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setMsfStatus = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearMsfStatus = function() {
  return this.setMsfStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasMsfStatus = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional MsfSensorMsgStatus sensor_status = 7;
 * @return {?proto.apollo.localization.MsfSensorMsgStatus}
 */
proto.apollo.localization.LocalizationEstimate.prototype.getSensorStatus = function() {
  return /** @type{?proto.apollo.localization.MsfSensorMsgStatus} */ (
    jspb.Message.getWrapperField(this, modules_localization_proto_localization_status_pb.MsfSensorMsgStatus, 7));
};


/**
 * @param {?proto.apollo.localization.MsfSensorMsgStatus|undefined} value
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
*/
proto.apollo.localization.LocalizationEstimate.prototype.setSensorStatus = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationEstimate} returns this
 */
proto.apollo.localization.LocalizationEstimate.prototype.clearSensorStatus = function() {
  return this.setSensorStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationEstimate.prototype.hasSensorStatus = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.localization.LocalizationStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.localization.LocalizationStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.localization.LocalizationStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.LocalizationStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && modules_common_proto_header_pb.Header.toObject(includeInstance, f),
    fusionStatus: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    gnssStatus: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    lidarStatus: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    measurementTime: (f = jspb.Message.getOptionalFloatingPointField(msg, 5)) == null ? undefined : f,
    stateMessage: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of LocalizationStatus as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.localization.LocalizationStatus.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.header;

  /** @type {?|undefined} */
  this.fusionStatus;

  /** @type {?|undefined} */
  this.gnssStatus;

  /** @type {?|undefined} */
  this.lidarStatus;

  /** @type {?|undefined} */
  this.measurementTime;

  /** @type {?|undefined} */
  this.stateMessage;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.localization.LocalizationStatus.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.localization.LocalizationStatus}
 */
proto.apollo.localization.LocalizationStatus.fromObject = function(obj) {
  var msg = new proto.apollo.localization.LocalizationStatus();
  obj.header && jspb.Message.setWrapperField(
      msg, 1, modules_common_proto_header_pb.Header.fromObject(obj.header));
  obj.fusionStatus != null && jspb.Message.setField(msg, 2, obj.fusionStatus);
  obj.gnssStatus != null && jspb.Message.setField(msg, 3, obj.gnssStatus);
  obj.lidarStatus != null && jspb.Message.setField(msg, 4, obj.lidarStatus);
  obj.measurementTime != null && jspb.Message.setField(msg, 5, obj.measurementTime);
  obj.stateMessage != null && jspb.Message.setField(msg, 6, obj.stateMessage);
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.localization.LocalizationStatus}
 */
proto.apollo.localization.LocalizationStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.localization.LocalizationStatus;
  return proto.apollo.localization.LocalizationStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.localization.LocalizationStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.localization.LocalizationStatus}
 */
proto.apollo.localization.LocalizationStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new modules_common_proto_header_pb.Header;
      reader.readMessage(value,modules_common_proto_header_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {!proto.apollo.localization.MeasureState} */ (reader.readEnum());
      msg.setFusionStatus(value);
      break;
    case 3:
      var value = /** @type {!proto.apollo.localization.MeasureState} */ (reader.readEnum());
      msg.setGnssStatus(value);
      break;
    case 4:
      var value = /** @type {!proto.apollo.localization.MeasureState} */ (reader.readEnum());
      msg.setLidarStatus(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMeasurementTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStateMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.localization.LocalizationStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.localization.LocalizationStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.localization.LocalizationStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.localization.LocalizationStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      modules_common_proto_header_pb.Header.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional apollo.common.Header header = 1;
 * @return {?proto.apollo.common.Header}
 */
proto.apollo.localization.LocalizationStatus.prototype.getHeader = function() {
  return /** @type{?proto.apollo.common.Header} */ (
    jspb.Message.getWrapperField(this, modules_common_proto_header_pb.Header, 1));
};


/**
 * @param {?proto.apollo.common.Header|undefined} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
*/
proto.apollo.localization.LocalizationStatus.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional MeasureState fusion_status = 2;
 * @return {!proto.apollo.localization.MeasureState}
 */
proto.apollo.localization.LocalizationStatus.prototype.getFusionStatus = function() {
  return /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.apollo.localization.MeasureState} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.setFusionStatus = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearFusionStatus = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasFusionStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MeasureState gnss_status = 3;
 * @return {!proto.apollo.localization.MeasureState}
 */
proto.apollo.localization.LocalizationStatus.prototype.getGnssStatus = function() {
  return /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.apollo.localization.MeasureState} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.setGnssStatus = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearGnssStatus = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasGnssStatus = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MeasureState lidar_status = 4;
 * @return {!proto.apollo.localization.MeasureState}
 */
proto.apollo.localization.LocalizationStatus.prototype.getLidarStatus = function() {
  return /** @type {!proto.apollo.localization.MeasureState} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.apollo.localization.MeasureState} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.setLidarStatus = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearLidarStatus = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasLidarStatus = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double measurement_time = 5;
 * @return {number}
 */
proto.apollo.localization.LocalizationStatus.prototype.getMeasurementTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.setMeasurementTime = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearMeasurementTime = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasMeasurementTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string state_message = 6;
 * @return {string}
 */
proto.apollo.localization.LocalizationStatus.prototype.getStateMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.setStateMessage = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.localization.LocalizationStatus} returns this
 */
proto.apollo.localization.LocalizationStatus.prototype.clearStateMessage = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.localization.LocalizationStatus.prototype.hasStateMessage = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * @enum {number}
 */
proto.apollo.localization.MeasureState = {
  OK: 0,
  WARNNING: 1,
  ERROR: 2,
  CRITICAL_ERROR: 3,
  FATAL_ERROR: 4
};

goog.object.extend(exports, proto.apollo.localization);
